import type {Metadata} from "next";

import Link from "next/link";

import "@/shared/styles/globals.css";
import {SpaceGrotesk} from "@/shared/styles/foundations/fonts";
import {Toaster} from "@/shared/components/toast/toast";

export const metadata: Metadata = {
  title: "nextjs-template",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  const fonts = SpaceGrotesk.variable;

  return (
    <html suppressHydrationWarning className={fonts} lang="en">
      <body>
        <Toaster>
          <header className="text-xl leading-16 font-bold">
            <Link href="/">nextjs-template</Link>
          </header>
          {children}
          <footer className="text-center leading-16 opacity-70">nextjs-template</footer>
        </Toaster>
      </body>
    </html>
  );
}
